const featuredCityData = [
  {
    id: 1,

    img: "https://images.pexels.com/photos/3886260/pexels-photo-3886260.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "zarqa russifa, lora",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Delhi is a city where ancient and modern blend seamlessly together. It is a place that not only touches your pulse but even fastens it to a frenetic speed. Home to millions of dreams, the capital of India",
    rating: 4,
    hotels: 1745,
  },
  {
    id: 2,

    img: "https://images.pexels.com/photos/399187/pexels-photo-399187.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "mondial",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Jaipur is known as much for its fascinating monuments and colorful markets as it is for its gorgeous handloom garments and wonderfully laid-out gardens. It is really not very difficult to fall in love with Jaipur the moment you land here",
    rating: 3,
    hotels: 1275,
  },
  {
    id: 3,

    img: "https://images.pexels.com/photos/114296/pexels-photo-114296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "clasico",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Goa is one of the most visited destinations in India, which is extremely popular for its beaches, rave parties, nightlife, flea markets, Casinos, Lip smacking cuisines, Portuguese style houses and colonial churches",
    rating: 5,
    hotels: 1653,
  },
  {
    id: 4,

    img: "https://images.pexels.com/photos/2652287/pexels-photo-2652287.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Kashmir",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Kashmir Valley is one of the top tourist destinations of India. Gulmarg, one of the most popular ski resort destinations in India, is also home to the world's highest green golf course",
    rating: 3,
    hotels: 945,
  },
  {
    id: 5,

    img: "https://images.pexels.com/photos/1378425/pexels-photo-1378425.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Mumbai",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Mumbai, previously known as Bombay is one of the most populous and biggest cities of Maharashtra.Also the biggest metropolis of this state, Mumbai is also popular as the entertainment and financial capital",
    rating: 5,
    hotels: 2454,
  },
  {
    id: 6,

    img: "https://images.pexels.com/photos/15818644/pexels-photo-15818644/free-photo-of-men-playing-football-indoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    name: "Leh Ladakh",
    countryImg: "/hotel-booking-app/images/flag.png",
    desc: "Ladakh is majorly popular amongst the adventurers who feel welcomed by the number of adrenaline rushing activities offered here. The union territory is amongst the top trekking destinations in India",
    rating: 2,
    hotels: 245,
  },
];

const citySliderData = [
  {
    id: 1,
    img: "/hotel-booking-app/images/cities/indiagate.webp",
    name: "New Delhi",
    property: 1745,
  },
  {
    id: 2,
    img: "/hotel-booking-app/images/cities/jaipur.jpg",
    name: "Jaipur",
    property: 1420,
  },
  {
    id: 3,
    img: "/hotel-booking-app/images/cities/goa.jpg",
    name: "Goa",
    property: 1745,
  },
  {
    id: 4,
    img: "/hotel-booking-app/images/cities/kashmir.jpg",
    name: "Kashmir",
    property: 1845,
  },
  {
    id: 5,
    img: "/hotel-booking-app/images/cities/mumbai1.jpg",
    name: "Mumbai",
    property: 3745,
  },
  {
    id: 6,
    img: "/hotel-booking-app/images/cities/ladakh.jpg",
    name: "Leh Ladakh",
    property: 845,
  },
  {
    id: 7,
    img: "/hotel-booking-app/images/cities/indiagate.webp",
    name: "New Delhi",
    property: 1745,
  },
  {
    id: 8,
    img: "/hotel-booking-app/images/cities/jaipur.jpg",
    name: "Jaipur",
    property: 1420,
  },
  {
    id: 9,
    img: "/hotel-booking-app/images/cities/goa.jpg",
    name: "Goa",
    property: 1745,
  },
  {
    id: 10,
    img: "/hotel-booking-app/images/cities/kashmir.jpg",
    name: "Kashmir",
    property: 1845,
  },
  {
    id: 11,
    img: "/hotel-booking-app/images/cities/mumbai1.jpg",
    name: "Mumbai",
    property: 3745,
  },
  {
    id: 12,
    img: "/hotel-booking-app/images/cities/ladakh.jpg",
    name: "Leh Ladakh",
    property: 845,
  },
];

const propertySliderData = [
  {
    id: 1,
    img: "/hotel-booking-app/images/properties/hotelroom.jpeg",
    name: "Hotels",
    property: 3545,
  },
  {
    id: 2,
    img: "/hotel-booking-app/images/properties/apartment.jpeg",
    name: "Apartments",
    property: 3420,
  },
  {
    id: 3,
    img: "/hotel-booking-app/images/properties/resort.jpeg",
    name: "Resorts",
    property: 2745,
  },
  {
    id: 4,
    img: "/hotel-booking-app/images/properties/motel.jpeg",
    name: "Motels",
    property: 1745,
  },
  {
    id: 5,
    img: "/hotel-booking-app/images/properties/villa.jpg",
    name: "Villas",
    property: 2845,
  },
  {
    id: 6,
    img: "/hotel-booking-app/images/properties/farmhouse.jpeg",
    name: "Farm Houses",
    property: 1245,
  },
  {
    id: 7,
    img: "/hotel-booking-app/images/properties/hotelroom.jpeg",
    name: "Hotels",
    property: 3545,
  },
  {
    id: 8,
    img: "/hotel-booking-app/images/properties/apartment.jpeg",
    name: "Apartments",
    property: 3420,
  },
  {
    id: 9,
    img: "/hotel-booking-app/images/properties/resort.jpeg",
    name: "Resorts",
    property: 2745,
  },
  {
    id: 10,
    img: "/hotel-booking-app/images/properties/villa.jpg",
    name: "Villas",
    property: 2845,
  },
  {
    id: 11,
    img: "/hotel-booking-app/images/properties/motel.jpeg",
    name: "Motels",
    property: 1745,
  },
  {
    id: 12,
    img: "/hotel-booking-app/images/properties/farmhouse.jpeg",
    name: "Farm Houses",
    property: 1245,
  },
];

const featuredCountryData = [
  {
    id: 1,
    img: "/hotel-booking-app/images/countries/indonesia.jpg",
    country: "INDONESIA",
    desc: "The biggest archipelago country in the world. UNESCO recognizes 9 World Heritage Sites in Indonesia,5 cultural and 4 natural sites provide an incredible value to visitors",
  },
  {
    id: 2,
    img: "/hotel-booking-app/images/countries/usa.jpg",
    country: "USA",
    desc: "Being one of the most important and developed countries in today's world, it has a huge number of tourists visiting each year",
  },
  {
    id: 3,
    img: "/hotel-booking-app/images/countries/italy.jpg",
    country: "ITALY",
    desc: "Italy attracts millions of tourists every year thanks to its fascinating culture, natural landscapes, artistic sites, and renowned cuisine.",
  },
  {
    id: 4,
    img: "/hotel-booking-app/images/countries/russia.jpg",
    country: "RUSSIA",
    desc: "Rich cultural heritage and natural variety places make Russia the most popular tourist destinations.",
  },
  {
    id: 5,
    img: "/hotel-booking-app/images/countries/france.jpg",
    country: "FRANCE",
    desc: "France is known all around the world for Paris and its monuments such as the Tower",
  },
];

const hotelListData = [
  {
    id: 1,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
    
    ],
    name: "Hotel Taj Palace New Delhi",
    place: "New Delhi",
    location: { lat: 28.6048, lng: 77.2234 },
    distance: 6.7,
    address: "Sardar Patel Marg, Chanakyapuri, 110021 New Delhi - India",
    offer: " Free Pack of Water Bottles",

    roomDetails: "Luxury Room with Bath Tub",
    bedDetails: "1 king size single bed",
    roomLeft: 5,
    rating: 5,
    reviews: 312,
    night: 1,
    adult: 2,
    children: 1,
    price: "25",

    otherCharges: "3,240",
  },
  {
    id: 2,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",

    ],
    name: "Hotel Hyatt Centric Janakpuri New Delhi",
    place: "New Delhi",
    location: { lat: 28.6289, lng: 77.0786 },
    distance: 12,
    address: "Janakpuri District Center, Janakpuri, 110058 New Delhi - India",
    offer: "Free Uniform",

    roomDetails: "King Room with Bath Tub",
    bedDetails: "1 extra-large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 275,
    night: 1,
    adult: 2,
    children: 0,
    price: "30",

    otherCharges: "714",
  },
  {
    id: 3,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",

    ],
    name: "Lemon Tree Premier - Delhi Airport",
    place: "New Delhi",
    location: { lat: 28.5516, lng: 77.1207 },
    distance: 13.6,
    address: "Aerocity Hospitality, IGI Airport, 110037 New Delhi - India",
    offer: " Free Pack of Water Bottles",

    roomDetails: "Superior Queen Room",
    bedDetails: "1 double bed",
    roomLeft: 2,
    rating: 4,
    reviews: 543,
    night: 2,
    adult: 2,
    children: 1,
    price: "20",

    otherCharges: "3,972",
  },
  {
    id: 4,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",

    ],
    name: "Hotel City Star Paharganj New Delhi",
    place: "New Delhi",
    location: { lat: 28.6448, lng: 77.2151 },
    distance: 1.3,
    address: "8718 D.B.Gupta Road, Paharganj, 110055 New Delhi - India",
 
    offer: " Free Pack of Water Bottles",

    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 3,
    reviews: 265,
    night: 1,
    adult: 2,
    children: 0,
    price: "20",

    otherCharges: "585",
  },
  {
    id: 5,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",

    ],
    name: "Radisson Blu Marina New Delhi",
    place: "New Delhi",
    location: { lat: 28.6338, lng: 77.2172 },
    distance: 0.5,
    address: "G-59, Connaught Place, 110001 New Delhi - India",
    offer: "Free Uniform",

    roomDetails: "Superior Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 5,
    rating: 5,
    reviews: 712,
    night: 1,
    adult: 2,
    children: 0,
    price: "25",

    otherCharges: "2,255",
  },
  {
    id: 6,
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png",

    ],
    name: "Hotel Tripple Tree - Karol Bagh",
    place: "New Delhi",
    location: { lat: 28.6613, lng: 77.1944 },
    distance: 4,
    address: "7A/73 WEA Channa Market Karol Bagh, 110005 New Delhi - India",
    offer: "Free Uniform",

    roomDetails: "Deluxe Double Room",
    bedDetails: "1 large double bed",
    roomLeft: 3,
    rating: 4,
    reviews: 43,
    night: 2,
    adult: 2,
    children: 1,
    price: "30",
    otherCharges: "396",
  },
];

export {
  featuredCityData,
  citySliderData,
  propertySliderData,
  featuredCountryData,
  hotelListData,
};
